audience: users
level: patch
reference: issue 4998
---
This fixes a bug in the Python client where an exception was raised on 300 HTTP
status.
